#! /bin/sh
cd src
pgf90 -c main.f
pgf90 -c circ.f
pgf90 -c interp.f
pgf90 -c netcdfio.f
pgf90 -o computeC main.o circ.o interp.o netcdfio.o -L/usr/global-7/sw/pgi/20.7/netcdf-fortran-4.5.3/lib -lm -lnetcdff
mv computeC ../bin
cd ..
